treewide: Fix error cause a function declaration is deprecated
Fixes warns on clang 15.0.0:

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ce/ce_service_legacy.c:1320:34: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_legacy()
                                 ^
                                  void
1 error generated.
make[4]: *** [../scripts/Makefile.build:365: drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ce/ce_service_legacy.o] Error 1
make[4]: *** Waiting for unfinished jobs....
  CC      drivers/staging/qcacld-3.0/components/target_if/pmo/src/target_if_pmo_ns.o
drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/target_if/regulatory/src/.tmp_target_if_reg_11d.o: no symbols
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/target_if/core/src/target_if_main.c:91:40: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct target_if_ctx *target_if_get_ctx()
                                       ^
                                        void
1 error generated.

Signed-off-by: Fiqri Ardyansyah <fiqri15072019@gmail.com>
Signed-off-by: Pranav Temkar <pranavtemkar@gmail.com>
Signed-off-by: WisnuArdhi <wisnuardi128@gmail.com>